### ISSUE TITLE
Extract and format subset of glossary for inclusion in book

### ISSUE THREAD

**Issue by gvwilson** [carpentries/glosario-r#12]
Additional use case: suppose you have written a book with bookdown, and have included glossary references. You would like to include those terms (and _only_ those terms) as a glossary in the book, so it should be possible to gather them while knitting the book (or in a separate pass).

**Comment by ian-flores** [comment]
going to start working on this. To be clear, the specific terms you mean would be defined in the YAML headers of the chapters or just calls to `gdef()`?
