### ISSUE TITLE
Using glosario package in R - works great!

### ISSUE THREAD

**Issue by yabellini** [carpentries/glosario-r#4]
The issue is just to tell you that I used the package in R reading this YAML (which I put together from the Spanish translation for T3) and it works perfect.
I use this code:
gl <- glosario::get_glossary(url = "https://raw.githubusercontent.com/gvwilson/teachtogether.tech/master/es/glossary.yml")
glosario::define("pull_request","es", glossary = gl)
glosario::define("pull_request","en", glossary = gl)

@ian-flores ;-)

**Comment by ian-flores** [comment]
Thanks Yanina! We will soon be adding support for Rmds and other features. This is really really cool! If you have any suggestions or changes you would like implemented please open an issue and we will triage it to incorporate ASAP. Saludos!
